@echo off
setlocal enabledelayedexpansion
echo.
echo [Step 4/5] Setting up filesystem protection and audit logging...
echo ------------------------------------------------------------

set WORKSPACE=%USERPROFILE%\ai-workspace
set LOG_DIR=%USERPROFILE%\ai-workload-logs
set LOG_FILE=%LOG_DIR%\commands.log

:: ── Create log directory ──────────────────────────────────────────────────────
if not exist "%LOG_DIR%" (
    mkdir "%LOG_DIR%"
    echo [ OK ]  Log directory created at: %LOG_DIR%
) else (
    echo [ OK ]  Log directory already exists.
)

:: ── Write a startup log entry ─────────────────────────────────────────────────
echo [%DATE% %TIME%] ai-workload-hardener setup run >> "%LOG_FILE%"
echo [ OK ]  Logging started. All security events will go to:
echo         %LOG_FILE%

:: ── Enable Windows audit policy for file access ───────────────────────────────
echo.
echo [FS]   Enabling Windows file access auditing...
echo        (requires a moment, runs silently)

:: Enable object access auditing
auditpol /set /subcategory:"File System" /success:enable /failure:enable >nul 2>&1
if errorlevel 1 (
    echo [ !! ]  Could not enable audit policy.
    echo         Try running setup.bat as Administrator for this step.
) else (
    echo [ OK ]  File system auditing enabled.
    echo         Windows will now log access to sensitive folders.
)

:: ── Set restrictive permissions on workspace ──────────────────────────────────
echo.
echo [FS]   Locking down workspace folder permissions...
echo        Only your user account will have access to: %WORKSPACE%

icacls "%WORKSPACE%" /inheritance:r /grant:r "%USERNAME%:(OI)(CI)F" >nul 2>&1
if errorlevel 1 (
    echo [ !! ]  Could not update workspace permissions.
    echo         Try running setup.bat as Administrator.
) else (
    echo [ OK ]  Workspace locked to current user only.
)

:: ── Write PowerShell monitor script ───────────────────────────────────────────
echo.
echo [FS]   Writing background file monitor script...

(
echo # AI Workload File Monitor
echo # Watches sensitive folders and logs unexpected access
echo # Generated by ai-workload-hardener
echo.
echo $sensitvePaths = @(
echo     "$env:USERPROFILE\.ssh",
echo     "$env:USERPROFILE\Documents",
echo     "$env:USERPROFILE\Desktop",
echo     "$env:APPDATA\Microsoft\Credentials"
echo ^)
echo.
echo $logFile = "$env:USERPROFILE\ai-workload-logs\file-access.log"
echo.
echo $watchers = foreach ($path in $sensitivePaths^) {
echo     if (Test-Path $path^) {
echo         $w = New-Object System.IO.FileSystemWatcher
echo         $w.Path = $path
echo         $w.IncludeSubdirectories = $true
echo         $w.EnableRaisingEvents = $true
echo.
echo         Register-ObjectEvent $w "Accessed" -Action {
echo             $msg = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] ACCESSED: $($Event.SourceEventArgs.FullPath)"
echo             Add-Content -Path $using:logFile -Value $msg
echo             Write-Host "[ALERT] Sensitive path accessed: $($Event.SourceEventArgs.FullPath)" -ForegroundColor Yellow
echo         }
echo     }
echo }
echo.
echo Write-Host "File monitor running. Watching sensitive folders..." -ForegroundColor Green
echo Write-Host "Log: $logFile" -ForegroundColor Gray
echo Write-Host "Press Ctrl+C to stop." -ForegroundColor Gray
echo.
echo while ($true^) { Start-Sleep 1 }
) > monitor.ps1

echo [ OK ]  monitor.ps1 written.
echo.
echo [FS]   To run the file monitor in the background:
echo        Right-click monitor.ps1 → "Run with PowerShell"
echo        It will alert you if anything touches your SSH keys or Documents.
echo.

:: ── Remind about Docker mount rules ───────────────────────────────────────────
echo [FS]   Docker mount reminder:
echo        In docker-compose.ai.yml, volumes are set to workspace only:
echo          %WORKSPACE%:/workspace:rw
echo.
echo        NEVER mount these in Docker:
echo          - C:\Users\%USERNAME%   (your entire home folder)
echo          - C:\Users\%USERNAME%\.ssh   (SSH keys)
echo          - C:\Windows   (system files)
echo.
echo [ OK ]  Filesystem step complete.
